#各SNS利用頻度週4-5回以上のダミー変数
mydata$Twitter_frequence<-rep(0)
mydata$Twitter_frequence[mydata$NET_Freq_01_MX==1]<-1
mydata$Twitter_frequence[mydata$NET_Freq_01_MX==2]<-2
mydata$Facebook_frequence<-rep(0)
mydata$Facebook_frequence[mydata$NET_Freq_02_MX==1]<-1
mydata$Facebook_frequence[mydata$NET_Freq_02_MX==2]<-2
mydata$Instagram_frequence<-rep(0)
mydata$Instagram_frequence[mydata$NET_Freq_03_MX==1]<-1
mydata$Instagram_frequence[mydata$NET_Freq_03_MX==2]<-2
mydata$LINE_frequence<-rep(0)
mydata$LINE_frequence[mydata$NET_Freq_05_MX==1]<-1
mydata$LINE_frequence[mydata$NET_Freq_05_MX==2]<-2
mydata$YouTube_frequence<-rep(0)
mydata$YouTube_frequence[mydata$NET_Freq_07_MX==1]<-1
mydata$YouTube_frequence[mydata$NET_Freq_07_MX==2]<-2

#各消費価値観
mydata$cheap<-mydata$SEN_01_MA
mydata$price<-mydata$SEN_02_MA
mydata$quality<-mydata$SEN_03_MA
mydata$namevalue<-mydata$SEN_04_MA
mydata$brand<-mydata$SEN_05_MA
mydata$design<-mydata$SEN_06_MA
mydata$TVdesign<-mydata$SEN_07_MA
mydata$popular<-mydata$SEN_08_MA
mydata$useful<-mydata$SEN_09_MA
mydata$reputation<-mydata$SEN_10_MA
mydata$trend<-mydata$SEN_11_MA
mydata$everyone<-mydata$SEN_12_MA
mydata$after<-mydata$SEN_13_MA
mydata$character<-mydata$SEN_14_MA
mydata$lifestyle<-mydata$SEN_15_MA
mydata$long<-mydata$SEN_16_MA
mydata$environment<-mydata$SEN_17_MA
mydata$safety<-mydata$SEN_18_MA
mydata$rental<-mydata$SEN_19_MA
mydata$second<-mydata$SEN_20_MA
mydata$used<-mydata$SEN_21_MA
mydata$private<-mydata$SEN_22_MA
mydata$order<-mydata$SEN_23_MA
mydata$information<-mydata$SEN_24_MA
mydata$money<-mydata$SEN_25_MA
mydata$teach<-mydata$SEN_26_MA
mydata$credit<-mydata$SEN_27_MA
mydata$like<-mydata$SEN_28_MA
mydata$japan<-mydata$SEN_29_MA
mydata$famous<-mydata$SEN_30_MA
mydata$friend<-mydata$SEN_31_MA
mydata$staff<-mydata$SEN_32_MA
mydata$none<-mydata$SEN_33_MA

#ダミー変数0=ない、1=ある
mydata$cheap<-rep(0)
mydata$cheap[mydata$SEN_01_MA==1]<-1
mydata$price<-rep(0)
mydata$price[mydata$SEN_02_MA==1]<-1
mydata$quality<-rep(0)
mydata$quality[mydata$SEN_03_MA==1]<-1
mydata$namevalue<-rep(0)
mydata$namevalue[mydata$SEN_04_MA==1]<-1
mydata$brand<-rep(0)
mydata$brand[mydata$SEN_05_MA==1]<-1
mydata$design<-rep(0)
mydata$design[mydata$SEN_06_MA==1]<-1
mydata$TVdesign<-rep(0)
mydata$TVdesign[mydata$SEN_07_MA==1]<-1
mydata$popular<-rep(0)
mydata$popular[mydata$SEN_08_MA==1]<-1
mydata$useful<-rep(0)
mydata$useful[mydata$SEN_09_MA==1]<-1
mydata$reputation<-rep(0)
mydata$reputation[mydata$SEN_10_MA==1]<-1
mydata$trend<-rep(0)
mydata$trend[mydata$SEN_11_MA==1]<-1
mydata$everyone<-rep(0)
mydata$everyone[mydata$SEN_12_MA==1]<-1
mydata$after<-rep(0)
mydata$after[mydata$SEN_12_MA==1]<-1
mydata$after[mydata$SEN_13_MA==1]<-1
mydata$character<-rep(0)
mydata$character[mydata$SEN_14_MA==1]<-1
mydata$lifestyle<-rep(0)
mydata$lifestyle[mydata$SEN_15_MA==1]<-1
mydata$long<-rep(0)
mydata$long[mydata$SEN_16_MA==1]<-1
mydata$environment<-rep(0)
mydata$environment[mydata$SEN_17_MA==1]<-1
mydata$safety<-rep(0)
mydata$safety[mydata$SEN_18_MA==1]<-1
mydata$rental<-rep(0)
mydata$rental[mydata$SEN_19_MA==1]<-1
mydata$second<-rep(0)
mydata$second[mydata$SEN_20_MA==1]<-1
mydata$used<-rep(0)
mydata$used[mydata$SEN_21_MA==1]<-1
mydata$private<-rep(0)
mydata$private[mydata$SEN_22_MA==1]<-1
mydata$order<-rep(0)
mydata$order[mydata$SEN_23_MA==1]<-1
mydata$information<-rep(0)
mydata$information[mydata$SEN_24_MA==1]<-1
mydata$money<-rep(0)
mydata$money[mydata$SEN_25_MA==1]<-1
mydata$teach<-rep(0)
mydata$teach[mydata$SEN_26_MA==1]<-1
mydata$credit<-rep(0)
mydata$credit[mydata$SEN_27_MA==1]<-1
mydata$like<-rep(0)
mydata$like[mydata$SEN_28_MA==1]<-1
mydata$japan<-rep(0)
mydata$japan[mydata$SEN_29_MA==1]<-1
mydata$famous<-rep(0)
mydata$famous[mydata$SEN_30_MA==1]<-1
mydata$friend<-rep(0)
mydata$friend[mydata$SEN_31_MA==1]<-1
mydata$staff<-rep(0)
mydata$staff[mydata$SEN_32_MA==1]<-1
mydata$none<-rep(0)
mydata$none[mydata$SEN_33_MA==1]<-1

#多項ロジットモデル
install.packages("mlogit")
library(mlogit)
logit_trend<-mlogit.data(mydata,shape="wide",choice="trend")
result_trend2<-mlogit(trend~0|Twitter_frequence+Facebook_frequence+Instagram_frequence+LINE_frequence+YouTube_frequence|0,logit_trend)
summary(result_trend2)